C0-2 EXPERIMENTS.

In [4]:
# Single Layer Perceptron (Manual Implementation) - Binary Classification

# Linearly separable dataset: AND logic
# x1 x2 -> y
# 0  0  -> 0
# 0  1  -> 0
# 1  0  -> 0
# 1  1  -> 1

X = [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]
y = [0, 0, 0, 1]

# Parameters
lr = 0.1
epochs = 50

# Initialize weights and bias
w = [0.0, 0.0]
b = 0.0

def predict(x):
    z = w[0] * x[0] + w[1] * x[1] + b
    return 1 if z >= 0 else 0

# Training
for epoch in range(1, epochs + 1):
    errors = 0
    for i in range(len(X)):
        y_hat = predict(X[i])
        e = y[i] - y_hat

        # Perceptron update rule
        w[0] += lr * e * X[i][0]
        w[1] += lr * e * X[i][1]
        b    += lr * e

        if e != 0:
            errors += 1

    print(f"Epoch {epoch:02d} -> errors={errors}, w={w}, b={b:.2f}")

    # Stop early if perfectly classified
    if errors == 0:
        break

# Testing / Output
print("\nFinal Model:")
print("Weights:", w)
print("Bias:", b)

print("\nPredictions:")
for i in range(len(X)):
    print(f"Input={X[i]}  Actual={y[i]}  Predicted={predict(X[i])}")


Epoch 01 -> errors=2, w=[0.1, 0.1], b=0.00
Epoch 02 -> errors=3, w=[0.2, 0.1], b=-0.10
Epoch 03 -> errors=3, w=[0.2, 0.1], b=-0.20
Epoch 04 -> errors=0, w=[0.2, 0.1], b=-0.20

Final Model:
Weights: [0.2, 0.1]
Bias: -0.20000000000000004

Predictions:
Input=[0, 0]  Actual=0  Predicted=0
Input=[0, 1]  Actual=0  Predicted=0
Input=[1, 0]  Actual=0  Predicted=0
Input=[1, 1]  Actual=1  Predicted=1


In [5]:
import numpy as np

# Sigmoid activation and derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# XOR dataset
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([[0], [1], [1], [0]])

# Network structure
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.5    # learning rate

# Initialize weights
np.random.seed(1)
W_h = np.random.randn(input_size, hidden_size)
b_h = np.zeros((1, hidden_size))

W_o = np.random.randn(hidden_size, output_size)
b_o = np.zeros((1, output_size))

# Training
epochs = 10000
for epoch in range(epochs):
    # --------- Forward Propagation ---------
    hidden_input = np.dot(X, W_h) + b_h
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W_o) + b_o
    output = sigmoid(final_input)

    # --------- Backpropagation ---------
    error = y - output
    d_output = error * sigmoid_derivative(output)

    hidden_error = d_output.dot(W_o.T)
    d_hidden = hidden_error * sigmoid_derivative(hidden_output)

    # Update weights
    W_o += hidden_output.T.dot(d_output) * lr
    b_o += np.sum(d_output, axis=0, keepdims=True) * lr

    W_h += X.T.dot(d_hidden) * lr
    b_h += np.sum(d_hidden, axis=0, keepdims=True) * lr

# Final predictions
print("\nFinal Predictions:")
print(output.round())



Final Predictions:
[[0.]
 [1.]
 [1.]
 [0.]]


In [6]:
pip install scikit-learn

  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 6.4 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/8.0 MB 4.6 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.0 MB 5.0 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.0 MB 5.6 MB/s eta 0:00:01
   -------------------------- ------------- 5.2/8.0 MB 5.6 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 6.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   - -------------------------------------- 1.0/38.5 MB 5.4 MB/s eta 0:00:07
   -- ------------------------------------- 2.6/38.5 MB 6.4 MB/s eta 0:00:06
   ---- ----------------------------------- 4.2/38.5 MB 6.9 MB/s eta 0:00:05
   ----- --------------------


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd

# Load dataset (Iris dataset)
data = load_iris()
X = data.data
y = data.target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Create MLP model
model = MLPClassifier(
    hidden_layer_sizes=(10, 10),
    max_iter=1000,
    activation='relu',
    solver='adam',
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", acc)
print("Confusion Matrix:\n", cm)


Accuracy: 0.9777777777777777
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [8]:
import random

# Objective function: maximize f(x) = x^2
def fitness(x):
    return x * x

# Generate random chromosome (integer between -10 and 10)
def create_chromosome():
    return random.randint(-10, 10)

# Mutation
def mutate(x):
    if random.random() < 0.1:  # mutation rate
        x += random.choice([-1, 1])
    return x

# Crossover
def crossover(parent1, parent2):
    return (parent1 + parent2) // 2

# GA setup
population_size = 6
generations = 20

# Initial population
population = [create_chromosome() for _ in range(population_size)]

for gen in range(generations):
    # Evaluate fitness
    scored = [(chrom, fitness(chrom)) for chrom in population]
    scored.sort(key=lambda x: x[1], reverse=True)

    print(f"Generation {gen+1}, Best: {scored[0]}")

    # Selection: choose top 2
    parents = [scored[0][0], scored[1][0]]

    # Create new population
    new_population = parents[:]

    while len(new_population) < population_size:
        child = crossover(parents[0], parents[1])
        child = mutate(child)
        new_population.append(child)

    population = new_population

# Final best solution
best = max(population, key=lambda x: fitness(x))
print("\nOptimal Solution Found:", best, "Fitness =", fitness(best))


Generation 1, Best: (-7, 49)
Generation 2, Best: (-7, 49)
Generation 3, Best: (-7, 49)
Generation 4, Best: (-7, 49)
Generation 5, Best: (-7, 49)
Generation 6, Best: (-7, 49)
Generation 7, Best: (-7, 49)
Generation 8, Best: (-7, 49)
Generation 9, Best: (-7, 49)
Generation 10, Best: (-7, 49)
Generation 11, Best: (-7, 49)
Generation 12, Best: (-7, 49)
Generation 13, Best: (-7, 49)
Generation 14, Best: (-7, 49)
Generation 15, Best: (-7, 49)
Generation 16, Best: (-7, 49)
Generation 17, Best: (-7, 49)
Generation 18, Best: (-7, 49)
Generation 19, Best: (-7, 49)
Generation 20, Best: (-7, 49)

Optimal Solution Found: -7 Fitness = 49


In [9]:
import numpy as np
import random
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

# Load dataset
data = load_iris()
X = data.data
y = data.target
n_features = X.shape[1]

# GA parameters
population_size = 6
generations = 10
mutation_rate = 0.1

# Create a random chromosome (binary: 1 = select feature)
def create_chromosome():
    return np.random.randint(0, 2, n_features)

# Fitness: accuracy using selected features
def fitness(chrom):
    if np.sum(chrom) == 0:  # avoid empty selection
        return 0
    selected = X[:, chrom == 1]
    X_train, X_test, y_train, y_test = train_test_split(
        selected, y, test_size=0.3, random_state=42
    )
    model = KNeighborsClassifier()
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    return accuracy_score(y_test, preds)

# Crossover
def crossover(p1, p2):
    point = random.randint(1, n_features - 1)
    return np.concatenate([p1[:point], p2[point:]])

# Mutation
def mutate(chrom):
    for i in range(n_features):
        if random.random() < mutation_rate:
            chrom[i] = 1 - chrom[i]
    return chrom

# Initial population
population = [create_chromosome() for _ in range(population_size)]

# GA loop
for gen in range(generations):
    scores = [(chrom, fitness(chrom)) for chrom in population]
    scores.sort(key=lambda x: x[1], reverse=True)

    print(f"Generation {gen+1}, Best Accuracy: {scores[0][1]} Chromosome: {scores[0][0]}")

    parents = [scores[0][0], scores[1][0]]
    new_population = parents[:]

    while len(new_population) < population_size:
        child = crossover(parents[0], parents[1])
        child = mutate(child)
        new_population.append(child)

    population = new_population

# Final selected features
best = max(population, key=lambda c: fitness(c))
print("\nBest Feature Subset:", best)
print("Best Accuracy:", fitness(best))


Generation 1, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 2, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 3, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 4, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 5, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 6, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 7, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 8, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 9, Best Accuracy: 1.0 Chromosome: [1 1 1 1]
Generation 10, Best Accuracy: 1.0 Chromosome: [1 1 1 1]

Best Feature Subset: [1 1 1 1]
Best Accuracy: 1.0
